dist: trusty
sudo: required

language: c

notifications:
  email: false

services:
  - cassandra
  - docker

env:
  global:
    - OPENSSL=1.0.2l
    - OPENRESTY=1.11.2.4
    - LUAROCKS=2.4.3
    - KONG=0.11.0
    - INSTALL_CACHE=$HOME/install-cache
    - DOWNLOAD_CACHE=$HOME/download-cache

before_install:
  - source .ci/prepare_env.sh

install:
  - source .ci/install.sh

script:
  - /bin/bash .ci/run_tests.sh

cache:
  directories:
    - $DOWNLOAD_CACHE
    - $INSTALL_CACHE
